### PR TITLE
Added my-button which lots of customization

### PR DESCRIPTION
**Pull request by Haider-Ali-Dev**
Added `my-button`
- You can change its width 
- Add classes
- typeButtton prop which can be `primary`, `warning` or `black`

### CODE REVIEW

**Comment by r4pt0s** [comment]
@Haider-Ali-Dev
It would be good to be able to change the color of the component depending on the type.

And a place where users can pass a icon which should be placed on the button properly as well.

**Comment by Haider-Ali-Dev** [comment]
@r4pt0s I will try to add more customization

**Comment by Haider-Ali-Dev** [comment]
@r4pt0s  I added more customization also added a icon library so people can added icon classed in icon props which straight away got to class attribute, I also added color props as you told me to. 
Here's the link of library i used got the icons [https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css](https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css)

**Comment by r4pt0s** [comment]
Looks good @Haider-Ali-Dev .
Just one thing, we will close this PR first.
Could you make another PR with the target branch dev instead of main?
We merge all PRs into dev first and Marge thd dev branch into main after we had a couple of PRs merged into dev.

**Comment by Haider-Ali-Dev** [comment]
@r4pt0s Should make another pull request but in dev branch?

**Comment by r4pt0s** [comment]
Exactly @Haider-Ali-Dev

**Pull request closed without merging**
